### ISSUE TITLE
[todo-mvp-dagger] Why Repository is Singleton

### ISSUE THREAD

**Issue by honnyc4** [googlesamples/android-architecture#259]
Hi,

If I have multiple repositories, I will have to do this ?

```
public TasksRepositoryComponent getTasksRepositoryComponent() {
        return mRepositoryComponent;
    }

public UserRepositoryComponent getUserRepositoryComponent() {
        return mRepositoryComponent;
    }

public TicketRepositoryComponent getTicketRepositoryComponent() {
        return mRepositoryComponent;
    }
```

**Comment by DanielNogueiraAndroid** [comment]
Hi,
If I understand your question right, I believe that the TasksRepository is a singleton because otherwise, with multiple instances of TasksRepository we can not take advantage of the consistent cache.
In my point of view, the question about how to handle more kinds of objects like on your example "User" and "Ticket" using repository structure is very interesting.
