### ISSUE TITLE
If the view references the presenter, and the presenter references the view, how does the app not leak?

### ISSUE THREAD

**Issue by jmalsoftware** [googlesamples/android-architecture#439]
I might have a rusty understanding or Java, or be missing something, but how does this architecture not leak memory? The P references the V and vice-versa. So while Android SDK might be able to call onDestroy(), Java garbage collector won't be able to reclaim both objects if they are strongly pointing to one another.

**Comment by digitalbuddha** [comment]
Great question! You need to manually drop the reference of the view from the presenter so that the presenter can be cleaned up by gc.  Take a look at how we are doing it in the dagger Mvp branch... We manually call detach view which breaks the connection between the fragment and the presenter https://github.com/googlesamples/android-architecture/blob/d1cacacded7caf9c572629b0426472fe8758df27/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/addedittask/AddEditTaskFragment.java#L65

This is similar to working with  listener where you need to unregister to not leak memory.

**Comment by jmalsoftware** [comment]
Very interesting -- thanks so much for your quick response!
