### ISSUE TITLE
Does it just  holds data in memory?

### ISSUE THREAD

**Issue by lfkabc** [googlesamples/android-architecture#477]
I checked out the "todo-mvp-clean" code and run, and add some to-do items, then restart my device. After restart success, I start the app, but there is no to-do items I have added before.

**Comment by lfkabc** [comment]
Or it can create new database Tasks.db wether the database is exist or not?

**Comment by brightdanielt** [comment]
Hello, I got a similar problem, but it's in branch master.
Sharing how I analysis it might help someone : )

1. Q:Is it a in memory database?
A:No, We build the database with Room.databaseBuilder() instead of Room.inMemoryDatabaseBuilder()[what is "in memory database"]
(https://developer.android.com/reference/android/arch/persistence/room/Room)

Q1. Is it a in memory database?
A1. No, We build the database with Room.databaseBuilder() instead of Room.inMemoryDatabaseBuilder()[what is "in memory database"](https://developer.android.com/reference/android/arch/persistence/room/Room)

**Comment by brightdanielt** [comment]
Hello, I got a similar problem, but it's in branch master.
Sharing how I analysis it might help someone : )

1. Q:Is it a in memory database?
A:No, We build the database with Room.databaseBuilder() instead of Room.inMemoryDatabaseBuilder().
[what is "in memory database"](https://developer.android.com/reference/android/arch/persistence/room/Room)

2. Q:Was the data cleared for query error and process killed at the same time 
A:No, After process was killed, I used adb shell to check data and it existed.

3.  Q:Is it possible we delete the data in code ourselves?
A:Yes, added break point to function about deleting data then debug,
I found remote database always replaces the local database every time  I restart the app.

Thanks this project ❤️
