### ISSUE TITLE
[todo-mvp] Repo clone does not work

### ISSUE THREAD

**Issue by szaske** [googlesamples/android-architecture#521]
Not sure where the problem is, but when I run:
`git clone https://github.com/googlesamples/android-architecture.git`

it only gives me a folder with a .git folder, the license, readme.md and other MD files.  No source code.  If I instead download the ZIP file I get the source code.  I thought I'd pass it along.

**Comment by DougSig** [comment]
You need to check out the branch you’re interested in. I.e. todo-mvp.

**Comment by szaske** [comment]
I understand, I've passed this along to github, as I suspect it's a UI problem on their end, for repo's like this that use branches to link different repos.  Probably not something that you can address.

**Comment by DougSig** [comment]
I don't understand the issue. The branches aren't linked other repos; they're all the same repo (android-architecture). If you checkout another branch (see the list on the README.md), all the source code files will show up. The master branch has no source code in it, only the files you mentioned.

**Comment by szaske** [comment]
Sorry I meant branch instead of repo.  I originally didn't see that you stored each version as separate branches in one repo.  As a newbie dev I'm used to seeing a file structure on github and when I clone it seeing the same thing on my machine.  Maybe you can make it more clear by adding to the README.MD in the master branch something like " This is the master branch.  The various architecture solutions are saved as branches, to checkout one of the architectures you'll need to switch to that branch.  You can see the full list of branches using `git branch -a`.  Just an idea.  Thanks for publishing all these patterns.  

One last thing, did you ever consider posting a non-MVP solution? All the code in the activity.  From a learning perspective it would be helpful.  Many of us go through the following learning curve:

1. Learn Java/Android
2. Make a Android app using activities only
3. Rebuild our app using MVP

Just a suggestion, thanks for creating these awesome pattern examples.

**Comment by DougSig** [comment]
We're happy you find it helpful and thanks for your suggestions. In the "Explore the Samples" section it says "This project hosts each sample app in separate repository branches. For more information, see the README.md file in each branch.". I guess we expect people to view the readme from the Github website (where I think its clear because of the markdown).

As far as non-MVP solutions, we have todo-mvvm-live and todo-mvvm-databinding :). We do not recommend putting all the code in the Activity and are likely not going to write a sample showing it. Though having a [codelab](https://codelabs.developers.google.com/?cat=Android) for that use-case wouldn't be a bad idea!
