### ISSUE TITLE
Sample MVVM with databinding?

### ISSUE THREAD

**Issue by mandrizzle** [googlesamples/android-architecture#59]
I was thinking about working on an example of this over the weekend. MVVM + databinding were made for each other and it would be nice if there was an example

**Comment by JoseAlcerreca** [comment]
Sounds good, it would be nice to showcase how [databinding](https://github.com/googlesamples/android-architecture/tree/todo-databinding/) would look like in a strict MVVM architecture. Make sure to base your code on that project so that we can see what changes easily.

Let's go this route first: https://github.com/googlesamples/android-architecture/wiki/Unofficial-samples
Thanks!

**Comment by djodjoni** [comment]
@JoseAlcerreca in your understanding is this what we refer to "vanilla MVVM" in  #138 ?

**Comment by JoseAlcerreca** [comment]
We need to assess this. We'll tackle MVVM and MVC after we're "done" with MVP (after v1). Stay tuned.

**Comment by ber4444** [comment]
This is merged in, although the readme is not updated. @JoseAlcerreca can you just tell me one thing - who is responsible for navigation in mvvm? E.g. if the view is a fragment, who would switch its layout to the next screen or who would replace it with another fragment? Unlike in mvp, the viewmodel (presenter) cannot do that - which seems to be a blocker problem with this architecture.

**Comment by JoseAlcerreca** [comment]
Yes, it's in development. The Navigator of each screen is responsible for navigation.

**Comment by florina-muntenescu** [comment]
MVVM with databinding sample can be found [here](https://github.com/googlesamples/android-architecture/tree/todo-mvvm-databinding)
