### ISSUE TITLE
[todo-mvvm-live] : Why is viewmodel and repository are using callbacks instead of livedata?

### ISSUE THREAD

**Issue by alexakasanjeev** [googlesamples/android-architecture#654]
In this [article](https://medium.com/androiddevelopers/viewmodels-and-livedata-patterns-antipatterns-21efaef74a54) under the section of Leaking ViewModel, it is advised to use live data all through. Then why the boiler plate code in todo-mvvm-live using callbacks.

**Comment by JoseAlcerreca** [comment]
Can you give more details?

**Comment by matrixyf** [comment]
Got the same question with @sanjeevyadavIT , why the code below is using callback rather than using liveData to comunicate between reposity and viewModel?
https://github.com/android/architecture-samples/blob/todo-mvvm-live/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/tasks/TasksViewModel.java
